### ISSUE TITLE
Can't configure a tree to auto refresh when a node is folded and then unfolded

### ISSUE THREAD

**Issue by DamienCassou** [spec-framework/spec#11]
To reproduce, evaluate this

``` smalltalk
TreeModel new
    childrenBlock: [ :number | Halt now. 1 to: number ];
    hasChildrenBlock: [ :number | true ];
    roots: (1 to: 10);
    openWithSpec
```

and then:
1. unfold node `10`
2. a debugger opens because of the `Halt now`
3. close the debugger
4. refold node `10`
5. unfold node `10`
6. the debugger is not reopened

This means that the `#childrenBlock:` is executed only once and then cached. In some scenarios, users will expect folding and then unfolding a node to refresh the node's children.

**Comment by BenjaminVanRyseghem** [comment]
I am waiting for your pull request ;)

**Comment by BenjaminVanRyseghem** [comment]
Fix by PR12
