### ISSUE TITLE
No way to prevent radio button from desactivating

### ISSUE THREAD

**Issue by webwarrior-ws** [spec-framework/spec#19]
Clicking again on activated radio button in radio button group will make all radio buttons inactive.
Which is not the way radio buttons work - they are supposed to represent **exactly one** choice (sometimes initial state is no choice, but it cannot be restored after user interaction).
Moreover, usage of reactive variables for RadioButtonModel state means there's no way to intercept desactivation and cancel it.

**Comment by BenjaminVanRyseghem** [comment]
That's true :)

I will have a look by tonight ;)

**Comment by BenjaminVanRyseghem** [comment]
Could you have a look a the https://github.com/spec-framework/spec/pull/21?
