### ISSUE TITLE
SubclassResponsibility: MyFirstWindow class had the subclass responsibility to implement #defaultSpec

### ISSUE THREAD

**Issue by alexispurslane** [spec-framework/spec#24]
Hi. I'm new to Pharo, (and Spec, by extension) and I was following the tutorial http://www.bahmanm.com/blogs/spec-part-1-basics that I had found online. I have this code for my #defaultSpec method:

``` smalltalk
defaultSpec
    ^ SpecColumnLayout new
        add: #labelGreeting;
        yourself
```

And here's my initializeWidgets method (if it helps):

``` smalltalk
initializeWidgets
    self instantiateModels: #(#labelGreeting #LabelModel).
    labelGreeting label: 'Hello, world!'
```

And yet, when I doIt `MyFirstWindow new openWithSpec`, I get this error:

```
SubclassResponsibility: MyFirstWindow class had the subclass responsibility to implement #defaultSpec
```

Thanks in advance!

**Comment by BenjaminVanRyseghem** [comment]
What is the class definition if `MyFirstWindow` ?

**Comment by alexispurslane** [comment]
Oh, nevermind, I just looked at your recent pull requests, thinking that maybe the tutorial I was using was out of date, and sure enough, it was! You guys moved the defaultSpec method to the "Class side". BTW, loving Spec and Pharo!
